function snowFall(t){t=t||{},this.maxFlake=t.maxFlake||300,/* 最多片数 */
this.flakeSize=t.flakeSize||10,/* 雪花形状 */
this.fallSpeed=t.fallSpeed||1}function snowCanvas(){var t=document.createElement("canvas");t.id="snowfall",t.width=window.innerWidth,t.height=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight),t.setAttribute("style","position:fixed; top: 0; left: 0; z-index: 1; pointer-events: none;"),document.getElementsByTagName("body")[0].appendChild(t),this.canvas=t,this.ctx=t.getContext("2d");
/* 窗口大小改变的处理 */
var e,n=this;window.onresize=function(){clearTimeout(e),e=setTimeout(function(){if(n.canvas&&n.flakes){var t=n.canvas.width;n.canvas.height;n.canvas.width=window.innerWidth,n.canvas.height=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);for(var e=0;e<n.flakes.length;e++){var i=n.flakes[e];t>n.canvas.width&&i.x>n.canvas.width&&(i.x=Math.random()*n.canvas.width)}}},150)}}function flakeMove(t,e,n,i){this.x=Math.floor(Math.random()*t),/* x坐标 */
this.y=Math.floor(Math.random()*e),/* y坐标 */
this.size=Math.random()*n+2,/* 形状 */
this.maxSize=n,/* 最大形状 */
this.speed=1*Math.random()+i,/* 坠落速度 */
this.fallSpeed=i,/* 坠落速度 */
this.velY=this.speed,/* Y方向速度 */
this.velX=0,/* X方向速度 */
this.stepSize=Math.random()/30,/* 步长 */
this.step=0/* 步数 */,this.canvas=null}function createFlakes(){for(var t=this.maxFlake,e=this.flakes=[],n=this.canvas,i=0;i<t;i++){var o=new flakeMove(n.width,n.height,this.flakeSize,this.fallSpeed);o.canvas=n,e.push(o)}}function drawSnow(){var t=this.maxFlake,e=this.flakes;ctx=this.ctx,canvas=this.canvas,that=this,ctx.clearRect(0,0,canvas.width,canvas.height);for(var n=0;n<t;n++)e[n].update(),e[n].render(ctx);this.loop=requestAnimationFrame(function(){drawSnow.apply(that)})}requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||function(t){setTimeout(t,1e3/60)},cancelAnimationFrame=window.cancelAnimationFrame||window.mozCancelAnimationFrame||window.webkitCancelAnimationFrame||window.msCancelAnimationFrame||window.oCancelAnimationFrame,snowFall.prototype.start=function(){snowCanvas.apply(this),createFlakes.apply(this),drawSnow.apply(this)},flakeMove.prototype.update=function(){this.x,this.y;this.velX*=.98,this.velY<=this.speed&&(this.velY=this.speed),this.velX+=Math.cos(this.step+=.05)*this.stepSize,this.y+=this.velY,this.x+=this.velX;var t=this.canvas?this.canvas.width:window.innerWidth,e=this.canvas?this.canvas.height:Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);(this.x>=t||this.x<=0||this.y>=e||this.y<=0)&&this.reset(t,e)},flakeMove.prototype.reset=function(t,e){this.x=Math.floor(Math.random()*t),this.y=0,this.size=Math.random()*this.maxSize+2,this.speed=1*Math.random()+this.fallSpeed,this.velY=this.speed,this.velX=0},flakeMove.prototype.render=function(t){var e=t.createRadialGradient(this.x,this.y,0,this.x,this.y,this.size);e.addColorStop(0,"rgba(255, 255, 255, 0.9)"),e.addColorStop(.5,"rgba(255, 255, 255, 0.5)"),e.addColorStop(1,"rgba(255, 255, 255, 0)"),t.save(),t.fillStyle=e,t.beginPath(),t.arc(this.x,this.y,this.size,0,2*Math.PI),t.fill(),t.restore()};var snow=new snowFall({maxFlake:150});snow.isRunning=!1,snow.isHome=!1;var originalStart=snow.start;
/* 仅首页下雪 */
function isHomePage(){var t=window.location.pathname;return!("/"!==t&&"/index.html"!==t&&!t.endsWith("/index"))||!(!document.body.classList.contains("home")&&!document.body.classList.contains("index"))}function checkAndStartSnow(){isHomePage()?snow&&!snow.isRunning?setTimeout(function(){isHomePage()&&snow.start()},50):snow&&snow.isRunning&&snow.isHome&&!snow.loop&&snow.resume():snow&&snow.isRunning&&snow.stop()}snow.start=function(){this.isRunning&&this.stop(),this.isRunning=!0,this.isHome=!0,originalStart.call(this)},snow.stop=function(){this.isRunning=!1,this.isHome=!1,this.loop&&(cancelAnimationFrame(this.loop),this.loop=null);var t=document.getElementById("snowfall");t&&t.parentNode&&t.parentNode.removeChild(t),this.canvas=null,this.ctx=null,this.flakes=[]},snow.pause=function(){this.loop&&(cancelAnimationFrame(this.loop),this.loop=null)},snow.resume=function(){this.isRunning&&this.canvas&&this.ctx&&!this.loop&&drawSnow.apply(this)},window.stopSnow=function(){snow&&snow.stop()},"loading"===document.readyState?document.addEventListener("DOMContentLoaded",function(){checkAndStartSnow(),window.addEventListener("scroll",function(){if(snow&&snow.isRunning&&snow.canvas){var t=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);t!==snow.canvas.height&&(snow.canvas.height=t)}})}):checkAndStartSnow();var pjaxSendHandler=function(){snow&&snow.isRunning&&snow.stop()};document.removeEventListener("pjax:send",pjaxSendHandler),document.addEventListener("pjax:send",pjaxSendHandler),document.addEventListener("pjax:complete",function(){setTimeout(checkAndStartSnow,100)}),document.addEventListener("visibilitychange",function(){document.hidden?snow&&snow.isRunning&&snow.loop&&snow.pause():setTimeout(checkAndStartSnow,100)});